# This is a config for E2B sandbox template.
# You can use template ID (qp6dldan1jjmtas21pfa) or template name (replitive-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("replitive-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("replitive-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('replitive-nextjs-test')

team_id = "e280554e-ed23-43b3-816a-d5f470683fa4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "replitive-nextjs-test"
template_id = "qp6dldan1jjmtas21pfa"
